#!/usr/bin/env sh

# Redeploys a personal project on my home server.
#
# The following environment variables should be defined:
#
# - PROJECT_NAME  The name of the directory within my personal PKGBUILDs.
# - SERVICE_NAME  The name of the systemd service to reload. If not declared
#                 the PROJECT_NAME will be used as the service name.

set -e

# Pre-execution checks
[ $EUID -ne 0 ] && { echo "Must be run as root" >&2 && exit 1 }
[ -z "$PROJECT_NAME" ] && { echo "PROJECT_NAME must be declared" >&2 && exit 1 }
SERVICE_NAME="${SERVICE_NAME:=$PROJECT_NAME}"

BUILD_TREE="$(mktemp -d)"
trap "{ rm -rf "$BUILD_TREE"; }" EXIT

# Download pkgbuild
git clone git@github.com:EvanPurkhiser/PKGBUILDs.git "$BUILD_TREE"
cd "$BUILD_TREE/$PROJECT_NAME"

# Build and install
docker pull whynothugo/makepkg:latest
docker run --rm -e EXPORT_PKG=1 -v "$PWD":/pkg whynothugo/makepkg
pacman -U --noconfirm ./*.pkg.tar.xz

# Restart service
systemctl restart $SERVICE_NAME.service
