#!/usr/bin/python2
#
# Toggles off my TV and speaker amp when my NES30 controller is powerd up/down

import dbus
import gobject
import subprocess

from dbus.mainloop.glib import DBusGMainLoop

dbus_loop = DBusGMainLoop()
bus = dbus.SystemBus(mainloop=dbus_loop)

# When the NES30 is connected / disconnected toggle power to the TV & amp
def cb(iface=None, mbr=None, path=None):
    if ('Connected' not in mbr):
        return

    subprocess.call(['irsend', 'SEND_ONCE', 'LG_AKB73975711', 'POWER'])
    subprocess.call(['irsend', 'SEND_ONCE', 'SMSL_RC36', 'POWER'])

# This is the address of my 8bitDo NES30 gamepad
bus.add_signal_receiver(cb, path='/org/bluez/hci0/dev_61_04_DF_50_71_01')

mainloop = gobject.MainLoop()
mainloop.run()
