name: build
on:
  push:
  schedule:
  - cron: '0 0 * * *'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
        - mutagen-git
        - python-httpie-oauth
        - keyfinder-cli-git
        - homebridge-git
        - waitress-git
        - oggfwd
        - dots-manager
        - setcolors-git
        - libkeyfinder-git
        - mkinitcpio-colors-git
        - media-center-automation
        - homebridge-tasmota-git
        - oggfwd-bzr
        - prolink-tools-git

    steps:
    - uses: actions/checkout@v2

    - name: Build package
      run: docker run -e EXPORT_PKG=1 -v ${{ github.workspace }}/${{ matrix.package }}:/pkg whynothugo/makepkg

    - name: Locate built package
      id: locate
      run: |
        pkg_path="$(ls ${{ github.workspace }}/${{ matrix.package }}/*.tar.xz)"
        echo ::set-output name=path::$pkg_path
        echo ::set-output name=name::$(basename $pkg_path)

    - uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.locate.outputs.name }}
        path: ${{ steps.locate.outputs.path }}
